# Generated by Django 4.1.3 on 2022-12-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_mascota_vehiculo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
