# Generated by Django 4.1.3 on 2022-12-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0005_delete_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueno', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('patente', models.CharField(max_length=9)),
            ],
        ),
    ]
